config/routes.rb
Rails.application.routes.draw do

  get 'search(/:search_item)' => 'search#index', as: :search

  get 'profiles/:username' => 'profiles#index', as: :profile_view
  post 'profiles/:username/follow' => 'profiles#follow', as: :follow
  post 'profiles/:username/unfollow' => 'profiles#unfollow', as: :unfollow
  post 'profiles/:username/block' => 'profiles#block', as: :block
  post 'profiles/:username/unblock' => 'profiles#unblock', as: :unblock


  resources :squawks

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  authenticated :user do
    devise_scope :user do
      root to: "squawks#index", as: :user_timeline
      delete '/signout', to: 'devise/sessions#destroy', as: :signout
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "static_pages#home", to: "devise/sessions#new"
    end
  end

  #route for sign-up wizard
  resources :after_signup

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user

  def index
    @squawks = @user.squawks.order("created_at DESC")
  end

  def follow
    if @user.cannot_follow?(@user)
      respond_to do |format|
        format.html {redirect_to :back, :notice => "You cannot follow this person."}
        format.js {}
      end
    else
      current_user.follow(@user)
      respond_to do |format|
        format.html {redirect_to :back, :notice => "You are now following #{@user.username}"}
        format.js {}
      end
    end
  end

  def unfollow
    current_user.stop_following(@user)
    respond_to do |format|
      format.html {redirect_to :back, :notice => "You are no longer following #{@user.username}"}
      format.js {:follow}
    end
  end

  def block
    if current_user == @user
      flash[:error] = "You cannot block yourself."
      redirect_to :back
    else
      current_user.block(@user)
      flash[:notice] = "You have now blocked #{@user.username}."
      current_user.stop_following(@user)
      redirect_to :back
    end
  end

  def unblock
    current_user.unblock(@user)
    flash[:notice] = "You have unblocked #{@user.username}."
    redirect_to :back
  end

  private

  def set_user
    @user = User.find_by "username = ?", params[:username]
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_miniprofile.html.erb
<div class="row text-center">
  <img src="<%= @user.try(:avatar) %>" onerror="this.src='<%=image_path("image1.jpg")%>';" alt="Missing Image">
</div>

<div class="row text-center">
    <p><%= @user.first_name %><p>
    <p><%= @user.username %><p>
    <p><%= @user.bio %><p>
</div>

<div class="row text-center">
  <div class="col-xs-4 text-center">
    <p>Squawks<br><%= @user.squawks.count %></p>
  </div>
  <div class="col-xs-4 text-center">
    <p>Following<br><%= @user.follow_count %></p>
  </div>
  <div class="col-xs-4 text-center">
    <p>Followers<br><%= @user.followers_count %></p>
  </div>
</div>

<div class="row text-center">
  <div class="col-lg-4 col-lg-offset-2">
    <!-- Following and unfollowing -->
    <% if current_user.following?(@user) %>
      <%= button_to "Unfollow", unfollow_path, :class => "btn btn-primary btn-sm", :method => :post, :remote => true %>
    <% else %>
      <%= button_to "Follow", follow_path, :class => "btn btn-primary btn-sm", :method => :post, :remote => true %>
    <% end %>
  </div>
  <div class="col-lg-4">
    <!-- Blocking and unblocking -->
    <% if current_user.blocks.include?(@user) %>
      <%= button_to "Unblock", unblock_path, :class => "btn btn-primary btn-sm", :method => :post %>
    <% else %>
      <%= button_to "Block", block_path, :class => "btn btn-primary btn-sm", :method => :post %>
    <% end %>
  </div>
</div>

app/views/profiles/follow.js.erb
$('#followable<%= @user.id %>').html("<%= escape_javascript(render :partial => "miniprofile") %>");

app/views/profiles/index.html.erb
<div class="col-xs-3" id="followable<%= @user.id %>">
  <%= render partial: 'miniprofile' %>
</div>

<div class="col-xs-6">
  <%= render partial: '/squawks/squawk', collection: @squawks %>
</div>

app/views/profiles/unfollow.js.erb
$('#followable<%= @user.id %>').html("<%= escape_javascript(render :partial => "miniprofile") %>");