config/routes.rb
Rails.application.routes.draw do

  get 'search(/:search_item)' => 'search#index', as: :search

  get 'profiles/:username' => 'profiles#index', as: :profile_view
  post 'profiles/:username/follow' => 'profiles#follow', as: :follow
  post 'profiles/:username/unfollow' => 'profiles#unfollow', as: :unfollow
  post 'profiles/:username/block' => 'profiles#block', as: :block
  post 'profiles/:username/unblock' => 'profiles#unblock', as: :unblock


  resources :squawks

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  authenticated :user do
    devise_scope :user do
      root to: "squawks#index", as: :user_timeline
      delete '/signout', to: 'devise/sessions#destroy', as: :signout
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "static_pages#home", to: "devise/sessions#new"
    end
  end

  #route for sign-up wizard
  resources :after_signup

end

app/controllers/after_signup_controller.rb
class AfterSignupController < ApplicationController
  include Wicked::Wizard
  steps :username, :avatar

  #defining the show field for first step
  def show
    @user = current_user
    render_wizard
  end

  # defining view for updates
  def update
    @user = current_user
    @user.update(user_params)
    render_wizard @user
  end

  def after_signup_params
    params.require(:user).permit(:first_name, :last_name, :username, :avatar)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :avatar)
  end

  private

  def redirect_to_finish_wizard(options = nil)
    redirect_to root_path , notice: "Thank you for signing up."
  end

end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/views/after_signup/avatar.html.erb
<div class="col-xs-6 col-xs-offset-3">
  <h1>Time to setup your Avatar and Bio</h1>
  <%= bootstrap_form_for(@user, :url => wizard_path, :method => :put) do |f| %>
    <%= f.text_field :avatar, :placeholder => "Avatar" %>
    <%= f.text_field :bio, :placeholder => "Biography" %>
    <%= f.submit 'Finish Profile', :class => 'btn btn-primary' %>
    <%= link_to 'Skip', squawks_path, :class => "btn btn-default" %>
  <% end %>
</div>

app/views/after_signup/registration.html.erb
<h1>Lets find out who you are</h1>
<%= bootstrap_form_for(@user, :url => wizard_path, :method => :put) do |f| %>
  <%= f.text_field :first_name, :placeholder => "First Name" %>
  <%= f.text_field :last_name, :placeholder => "Last Name" %>
  <%= f.text_field :email, :placeholder => "Email" %>
  <%= f.text_field :password, :placeholder => "Password" %>
  <%= f.text_field :password_confirmation, :placeholder => "Password Confirmation" %>
  <%= f.submit 'Next Step', :class => 'btn btn-primary' %>
<% end %>

app/views/after_signup/username.html.erb
<div class="col-xs-6 col-xs-offset-3">
  <h1>Let's pick a Name</h1>
  <%= bootstrap_form_for(@user, :url => wizard_path, :method => :put) do |f| %>
    <%= f.text_field :username, :placeholder => "Username" %>
    <%= f.submit 'Next Step', :class => 'btn btn-primary'%>
    <% end %>
</div>