config/routes.rb
Rails.application.routes.draw do

  get 'search(/:search_item)' => 'search#index', as: :search

  get 'profiles/:username' => 'profiles#index', as: :profile_view
  post 'profiles/:username/follow' => 'profiles#follow', as: :follow
  post 'profiles/:username/unfollow' => 'profiles#unfollow', as: :unfollow
  post 'profiles/:username/block' => 'profiles#block', as: :block
  post 'profiles/:username/unblock' => 'profiles#unblock', as: :unblock


  resources :squawks

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  authenticated :user do
    devise_scope :user do
      root to: "squawks#index", as: :user_timeline
      delete '/signout', to: 'devise/sessions#destroy', as: :signout
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "static_pages#home", to: "devise/sessions#new"
    end
  end

  #route for sign-up wizard
  resources :after_signup

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Squawker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="wrapper">
    <nav role="navigation" class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <i class="fa fa-twitter-square fa-3x pull-left"></i>
            <%= link_to "Squawker", root_path, class: "navbar-brand" %>
        </div>

        <div id="navbar">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "New Squawk", "#", class: "btn new-squawk" %></li>

              <!-- Only shows profile when a username has been saved to the db. -->
                <% if current_user.username? %>
                  <li><%= link_to "Profile", profile_view_path(username: current_user.username), :class => 'navbar-link' %></li>
                <% end %>
              <li><%= link_to "Logout", destroy_user_session_path, :class => 'navbar-link'  %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
            <% end %>
            <%= form_tag search_path, :method => :get, class: "navbar-form navbar-left" do %>
                <%= text_field_tag :search_item, params[:search_item], placeholder: 'Search...', :autocomplete => :off, class: "form-control"  %>
                <%= submit_tag "Search", class: "btn btn-primary" %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Hidden form for new squawks -->
    <div class="container">
      <div class="col-xs-6 col-xs-offset-3">
        <div class="new-squawk-form">
          <%= render partial: '/squawks/form' %>
        </div>
      </div>
    </div>

    <div class="dark-screen"></div>

    <!-- Shows errors when one is present -->
    <div class="container">
      <div class="text-center col-xs-3 col-xs-offset-9">
        <% if flash[:error] %>
          <p class='error'><%=h flash[:error] %></p>
        <% end %>
        <% if flash[:notice] %>
          <p class='notice'><%=h flash[:notice] %></p>
        <% end %>
      </div>

      <%= yield %>

    </div>

  </div>


  <div class="footer"></div>

</body>
</html>