config/routes.rb
Rails.application.routes.draw do

  get 'search(/:search_item)' => 'search#index', as: :search

  get 'profiles/:username' => 'profiles#index', as: :profile_view
  post 'profiles/:username/follow' => 'profiles#follow', as: :follow
  post 'profiles/:username/unfollow' => 'profiles#unfollow', as: :unfollow
  post 'profiles/:username/block' => 'profiles#block', as: :block
  post 'profiles/:username/unblock' => 'profiles#unblock', as: :unblock


  resources :squawks

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  authenticated :user do
    devise_scope :user do
      root to: "squawks#index", as: :user_timeline
      delete '/signout', to: 'devise/sessions#destroy', as: :signout
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "static_pages#home", to: "devise/sessions#new"
    end
  end

  #route for sign-up wizard
  resources :after_signup

end

app/models/squawk.rb
class Squawk < ActiveRecord::Base
  belongs_to :user
  validates_length_of :body, maximum: 170
  before_create :replace_with_link

  def self.timeline(user)
    following_ids = user.all_following.collect(&:id)
    all_ids = following_ids << user.id
    Squawk.where(user_id: all_ids).order("created_at DESC")
  end

  def replace_with_link
    if get_matches
      get_matches.each do |match|
        self.body.gsub!(match, create_search_link(match))
      end
    end
  end

  def create_search_link(word)
    "<a href='search/#{word}'>#{word}</a>"
  end

  def get_matches
    self.body.scan(/\B~\w*[a-zA-Z]+\w*/)
  end

end

app/controllers/squawks_controller.rb
class SquawksController < ApplicationController
  # before_action :set_squawk, only: [:show, :edit, :update, :destroy]

  # GET /squawks
  # GET /squawks.json
  def index
    @squawks = Squawk.timeline(current_user).page(params[:page]).per(20)
    @who_to_follow = User.all.sample(3)
  end

  # GET /squawks/1
  # GET /squawks/1.json
  def show
  end

  # GET /squawks/new
  def new
    @squawk = Squawk.new
  end

  # GET /squawks/1/edit
  def edit
  end

  # squawk /squawks
  # squawk /squawks.json
  def create
    @squawk = Squawk.new(squawk_params)
    # current_user.squawks << @squawk

    respond_to do |format|
      if current_user.squawks << @squawk
        format.html { redirect_to :back, notice: 'squawk was successfully created.' }
        format.json { render :show, status: :created, location: @squawk }
      else
        format.html { render :new }
        format.json { render json: @squawk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /squawks/1
  # PATCH/PUT /squawks/1.json
  def update
    respond_to do |format|
      if @squawk.update(squawk_params)
        format.html { redirect_to @squawk, notice: 'Squawk was successfully updated.' }
        format.json { render :show, status: :ok, location: @squawk }
      else
        format.html { render :edit }
        format.json { render json: @squawk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squawks/1
  # DELETE /squawks/1.json
  def destroy
    @squawk.destroy
    respond_to do |format|
      format.html { redirect_to squawks_url, notice: 'Squawk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_squawk
      @squawk = Squawk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def squawk_params
      params.require(:squawk).permit(:body)
    end
end

app/helpers/squawks_helper.rb
module SquawksHelper

  def resource_name
    :squawk
  end

  def resource
    @resource ||= Squawk.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:squawk]
  end

end

app/views/squawks/_form.html.erb
<%= bootstrap_form_for(@new_squawk) do |f| %>

  <div class="field">
    <%= f.text_area :body,
                    :label => "Squawk",
                    :id => "squawk-body-field",
                    :onkeyup => "if (this.value.length > 170) {
                                  document.getElementById('submit-squawk').disabled = true;
                                } else {
                                  document.getElementById('submit-squawk').disabled = false;
                                }" %>
  </div>

  <div class="actions">
    <%= f.submit "Make Squawk!", class: "btn btn-default", id: "submit-squawk" %>
  </div>

<% end %>

app/views/squawks/_homeprofile.html.erb
<div class="row text-center">
  <img src="<%= user.avatar %>" onerror="this.src='<%=image_path("image1.jpg")%>';" alt="Missing Image">
</div>

<div class="row text-center">
    <p><%= user.first_name %><p>
    <p><%= user.username %><p>
    <p><%= user.bio %><p>
</div>

<div class="row text-center">
  <div class="col-xs-4 text-center">
    <p><small>Squawks</small><br /><%= user.squawks.count %></p>
  </div>
  <div class="col-xs-4 text-center">
    <p><small>Following</small> <%= user.follows.count %></p>
  </div>
  <div class="col-xs-4 text-center">
    <p><small>Followers</small> <%= user.followers.count %></p>
  </div>
</div>

app/views/squawks/_new.html.erb
  <h1>Create a new Squawk</h1>

  <%= render 'form' %>

  <%= button_to 'Cancel', :back %>

app/views/squawks/_squawk.html.erb
<div class="row top-border">
  <div class="col-lg-3">
    <img src="<%= squawk.user.avatar %>" onerror="this.src='<%=image_path("image1.jpg")%>';" alt="Missing Image">
  </div>
  <div class="col-lg-9">
    <div class="row">
      <span>
        <%= link_to squawk.user.first_name, profile_view_path(username: squawk.user.username) %>
        <span class="light-text">@<%= squawk.user.username %></span>
      </span>
      <h4><%= raw(squawk.body) %></h4>
      <%= time_ago_in_words(squawk.created_at) %> ago
    </div>
  </div>
</div>

app/views/squawks/_who_to_follow.html.erb
<div class="row">
  <div class="col-xs-4">
    <img src="<%= user.avatar %>" onerror="this.src='<%=image_path("image1.jpg")%>';" alt="Missing Image">
  </div>

  <div class="col-xs-7 col-xs-offset-1">
    <p><%= link_to user.first_name, profile_view_path(username: user.username) %> <span class="light-text">@<%= user.username %></span><p>
    <!-- Following and unfollowing -->
    <% if current_user.following?(user) %>
      <%= button_to "Unfollow", unfollow_path(username: user.username), :class => "btn btn-primary btn-sm", :method => :post %>
    <% else %>
      <%= button_to "Follow", follow_path(username: user.username), :class => "btn btn-primary btn-sm", :method => :post %>
    <% end %>
  </div>
</div>

app/views/squawks/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/squawks/index.html.erb
<div class="col-xs-3">
  <%= render partial: 'homeprofile', locals: { user: current_user } %>
</div>

<div class="col-xs-6">
  <div id="squawks">
    <%= render partial: 'squawk', collection: @squawks %>
  </div>
  <%= paginate @squawks %>
</div>

<div class="col-xs-3">
  <% @who_to_follow.each do |user| %>
    <%= render partial: 'who_to_follow', locals: { user: user } %>
  <% end %>
</div>

app/views/squawks/index.js.erb
// From Rails Casts

$('#squawks').append('<%=j render(@squawks) %>');
<% if @squawks.next_page %>
  $('.pagination').replaceWith('<%=j paginate(@squawks) %>');
<% else %>
  $('.pagination').text("You've read everything. Go outside.");
<% end %>
<% sleep 0.3 %>

app/views/squawks/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/squawks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>